### ISSUE TITLE
입력문의 맨 앞 단어의 철자가 틀려도 수정되지 않습니다.

### ISSUE THREAD

**Issue by oldiron-ho** [9beach/hanspell#1]
다음과 같이 실행됩니다.
![image](https://user-images.githubusercontent.com/32806928/44175970-f66b7e80-a122-11e8-8acb-a7416ac8cd73.png)

https://github.com/9beach/hanspell/blob/d1ab29cfa8284bac03521e344d7f264243038b0c/lib/cli.js#L36
문장에서 바꿀단어를  찾아주는 위 정규식이 입력문의 맨앞에서 동작하지 않는거 같습니다. 이것을
` escaped = '(^|(?<=[^ㄱ-ㅎㅏ-ㅣ가-힣]))' + escaped + '((?=[^ㄱ-ㅎㅏ-ㅣ가-힣])|$)';`
과 같이 변경하면 되지 않을까 싶습니다. 뒤에 정규식은 바꾸지 않아도 입력문의 맨 뒷 단어에 대해 동작을 하지만, 문법적으로는 넣어주는게 맞지 않나 싶습니다.

**Comment by 9beach** [comment]
오, 고맙다. 고쳐서 버전 0.5.4로 올렸다.
