### ISSUE TITLE
[question] 서버 접속 오류

### ISSUE THREAD

**Issue by dlwlals0436** [9beach/hanspell#10]
안녕하세요!

hanspell로 긴 문단 교정을 시도할때 교정이 되다가 서버 접속 오류로 인해 몇 오타를 뛰어넘고, 다시 교정되는 문제가 생깁니다.
다음, 부산대 모두 이런 문제가 발생하고, 윈도우/ 맥 os 둘 다 테스트 해보았습니다.
짧은 문단은 잘 교정이 되지만, 몇달전엔 긴 문단 교정에도 편리하게 사용했어서 확인 부탁드리고 싶습니다. 
감사합니다!

-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
“으악이라니, -> “으악이라니,
“…제발 -> “… 제발
“…뭐요?” -> “… 뭐요?”
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
펴낸곳│나인 -> 펴낸 곳│나인
“우라지게 -> “우라지게
왔….” -> 왔….”
뒷걸음질 치고 -> 뒷걸음질치고
“실례합니다아.” -> “실례합니다.”
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다.
온더락 -> 온 더 락
…원래 -> … 원래

**Comment by 9beach** [comment]
비주얼 스튜디오 코드 한스펠 익스텐션<https://github.com/9beach/vscode-hanspell>의 리드미에는 위의 현상을 알렸는데 정작 한스펠에는 명시하지 않았네요.

말씀하신 현상이 존재합니다. 원인은 부산대 서버가 붐비면 이런 현상이 발생합니다. 그런데 다음 서버는 이런 현상이 발생한 적이 없습니다. 다음 서버에서도 그런 현상이 정말 있었는지 다시 확인 부탁드립니다.

**Comment by dlwlals0436** [comment]
한스펠로 다시 확인했고, 비쥬얼 스튜디오 익스텐션도 지금 막 사용해본 결과 다음 서버 접속 오류로 교정실패라는 팝업창이 뜨네요!

**Comment by 9beach** [comment]
제가 해서는 오류가 안납니다. 가끔씩 그러나요? 계속 그러나요? 교정하려는 긴 문장 공유 부탁합니다. 제가 해 볼께요.

**Comment by 9beach** [comment]
확인했습니다. 알려진 것보다 훨씬 다음 서버 오류도 많이 납니다. 들여다 보겠습니다.

**Comment by 9beach** [comment]
동시에 여러 요청을 허용하던 다음 서버가 이를 금지하면서 긴 문장 교정 시 오류가 발생하던 것을, 인터벌을 두고 요청함으로써 수정했습니다.

`npm Install -g hanspell` 명령어로 업데이트하세요. 버그 알려주셔서 고맙습니다.

**Comment by 9beach** [comment]
vscode 익스텐션도 수정했습니다. 인터벌을 1000자 마다 0.4초씩 둬서 기존보다 조금 늦게 교정됩니다.
