### ISSUE TITLE
node.js 프로젝트에서 spellCheckByDAUM 결과를 홈페이지에 출력하는 방법

### ISSUE THREAD

**Issue by UnDeFinedUsers** [9beach/hanspell#11]
안녕하세요. 현재 작은 Node.js 프로젝트를 하나 진행하고 있는데 간단한 온라인 맞춤법 검사기를 만들어보려고 합니다.

다름이 아니라 spellCheckByDAUM 함수에서 check 함수에 다른 variable을 전달할 수가 없어

제 수준에선 해당 프로젝트의 파일 수정 없이

어떻게 해당 결과를 다른 변수에 저장하고 웹 페이지에 출력할 수 있는지 좋은 방법이 떠오르지가 않습니다.

좋은 방법이 있다면 제시해 주시면 감사하겠습니다.

감사합니다!

**Comment by 9beach** [comment]
답신 늦어서 미안합니다. 다음 맞춤법 서비스를 호출하는 자바스크립트를 다른 사이트에서 호출할 수 없습니다. 이것은 저작권 문제가 아니라 보안 문제 때문에 일반적으로 불가능합니다. 물론 노드JS는 웹 서비스가 아니니 다음을 호출할 수 있고요.

그리고 변수에 할당하는 것은 소스 수정없이 됩니다. 리브미에 있는 다음의 예제를 확인하세요.

```javascript
// hanspell-example.js
const hanspell = require('hanspell');

const sentence = '리랜드는 얼굴 골격이 굵은게,';
const end = function () {
  console.log('// check ends');
};
const error = function (err) {
  console.error('// error: ' + err);
};

hanspell.spellCheckByDAUM(sentence, 6000, console.log, end, error);
hanspell.spellCheckByPNU(sentence, 6000, console.log, end, error);
```

위의 `console.log` 부분을 변수에 더하는 식으로 변경하면 됩니다.
