### ISSUE TITLE
daum api 호출 제한 관련 질문드립니다

### ISSUE THREAD

**Issue by yeonsunYang** [9beach/hanspell#17]
안녕하세요, daum 맞춤법 서비스 이용 중 문의드리고 싶은 것이 있습니다!

책 한 권 분량의 text파일 맞춤법을 교정하고 싶어서, 한 문단씩 계속 다음 api 호출하면서 교정을 했는데요, 

"-- 한스펠 오류: 다음 서버의 접속 오류로 일부 문장 교정에 실패했습니다."
위와 같은 오류 발생 시 무한대로 retry 하도록 코드를 짰습니다
그런데 어느 시점이 되니까 아예 다음 api 사용이 막혀버려서요..!

**혹시 분당 혹은 일당 api 호출수 제한이 있나요?**
얼마 간의 시간이 지나면 api 호출이 풀릴 수 있을지, 
이런 경우 제한을 회피할 수 있는 좋은 솔루션이 있을지 조언 부탁드립니다!! ㅠㅠ

**Comment by 9beach** [comment]
답신 늦어서 죄송합니다. 다음 뿐 아니라 대부분의 서비스는 호출 빈도에 제한을 둡니다. 그래서 저는 0.4초 단위로 호출했습니다. 물론 이것도 확실한 것은 아니지만 참고하세요.
