### ISSUE TITLE
UI 버전 아이디어 정리

### ISSUE THREAD

**Issue by 9beach** [9beach/hanspell#2]
고철, 읽고 의견 주기 바란다.

참고할 만한 맞춤법 검사기는, 기본 웹 컨트롤인 `textarea`의 맞춤법 검사 기능과 VS Code 등 IDE의 `lint` 플러그인이라고 생각한다. 둘 다 실시간으로 문제가 있는 단어에 밑줄이 생긴다. `textarea`의 경우, 문제 단어를 클릭하면 추천 단어가 있으면 팝업으로 보여준 뒤 사용자가 선택하면 해당 단어가 변경되며, `lint` 플러그인은 팝업으로 설명도 뜬다.

우리는 실시간으로 검색하기 힘들어서 교정 버튼을 누를 때마다 부산대/다음 서버에서 검색한 뒤 로컬 디비를 갱신하면 될 것 같다. 교정한 토큰과 무시한 토큰을 모두 로컬에 저장하고, 맞춤법을 틀린 복수개의 단어를 하나의 키로 리버스 인덱스를 구성할 필요가 있다.

기존의 간단한 한글 맞춤법 검사 앱은, 교정 모드에서는 편집이 금지되며 의심 단어만 메뉴를 통해 허용하는 경우가 많다. 다른 문장도 고치고 싶을 때가 많아서 나는 이렇게 모드를 구분하는 방식을 좋아하지 않는다.

일렉트론 기반으로 작성하되, 편집기 웹 컨트롤로 `draft.js`가 좋아 보이니 이것과 `hanspell` 이용해서 아래의 순서대로 처리하려 한다.

1. `draft.js`에서 문장을 편집한다. 로컬에서 디비 검색 결과에 걸리면 실시간으로 빨간 점선을 긋는다.
2. 교정 버튼을 누르면 `hanspell` 라이브러리로 교정된 문장과 정보를 가져온다. 교정 버튼 누르면 그때 교정한다고 생각하기 보다는 교정 버튼은 주어진 문장을 통해 로컬 디비를 갱신하기 위해서라고 생각하는 편이 자연스럽다.
3. 기존 문장에서 교정해야 할 부분을 링크로 처리하고 링크의 스타일은 빨간색 점선으로 지정한다. 참고로, `draft.js`가 문장에 링크 걸기 기능을 제공한다.
4. `링크 클릭 핸들러`는 추천 단어와 설명을 보여준다.
5. `추천 단어 클릭 핸들러`는 문장을 수정한 뒤, 다시 위의 3단계로 돌아간다. 즉 1~3단계가 사용자에 의해 반복되며 4, 5는 콜백 함수이다.

추가로 생각할 수 있는 일은, `lint`나 Vim 플러그인을 만드는 것과, 위의 맞춤법 검사기를 작가를 위한 편집기 수준으로 개선하는 일이다.  

다음의 세부 기능을 생각할 수 있다.

* 검색 결과를 로컬 디비에 누적하면서 이를 통한 실시간 교정
* 무시한 토큰 기억
* 무시한 토큰 리스트 편집
* 부산대/다음 서버 선택
* 전체 문장에서 수정/해당 단어만 수정
* `draft.js` 기능 중 노출해야 할 것
  * 찾기
  * 바꾸기
  * 리치 텍스트 기능 불필요
  * 이 밖에 또 무엇이 있을까?
* 파일로 저장하기, 파일 버전 관리 등은 불필요
* 부산대 결과 후처리 필요 (불필요하게 긴 결과를 보여줘서 리버스 인덱스 구성하기 전에 간단한 처리를 해야 한다. 가령 `이밖에 또 무엇이`를 `이 밖에 또 무엇이`로 고치라고 한다.  `이 밖에`만 저장하면 된다.) -> 엄밀한 논리적 검증 필요
* 맞춤법에 걸리지 않았는데 사용자가 수정한 단어 로컬 디비에 추가 (`읽어보고`를 `읽고`로 고친 경우 등에 대해 사용자가 직접 추가하기 기능 제공)

**Comment by oldiron-ho** [comment]
웹컨트롤을 쓰고, 다음/부산대 서버와 통신을 한다면, 기본 서비스를 해주는 서버의 존재가 필요하고 전체 방향이 웹서비스라고 보여지는데, 이때 로컬 디비라는 것을 어떻게 생성할것인가는 문제가 될거라고 봄.

여기서, 로컬 디비가 현재 창에서만 작동하는 일시적인 것인지, 아니면 나의 설정과 교정들을 영구히 기억하는  것인지에 대한 정의가 필요할거 같은데, 후자는 자바스크립트가 로컬 파일에 직접 데이터를 쓸 수 가 없는 것으로 알고 있음. 
그렇다면 서버에 설정을 올렸다가 실행할때 브라우저에 두고 실행해야 한다는 이야기인데, 그렇게 되면 서버 구성이 너무 복잡해져버릴거 같음.

그외는 `draft.js` 를 좀 찾아보고 생각해 보겠음.

**Comment by 9beach** [comment]
어차피 외부 웹 서비스를 연결해야 해서 일렉트론으로 개발하는데 굳이 웹 스토리지를 이용하는 장점이 있을까?

**Comment by 9beach** [comment]
별도의 프로젝트 생성: https://github.com/9hobbes/h-draft
