### ISSUE TITLE
라이선스 구매 문의 

### ISSUE THREAD

**Issue by heartcored98** [9beach/hanspell#8]
안녕하세요? 저희는 차량 문제 해결 상담 서비스 닥터차를 운영하고 있는데요.
상담사 분들이 연령대가 높아서 고객 분들에게 맞춤법이 다소 안 맞는 답변을 드리고 있어 이를 개선하고자 합니다.
희망하는 사용 형태는 크롬 확장 프로그램으로 만들어서 Grammly 프로그램과 같이 상담사 웹 콘솔에서 답변을 작성하면 일정 주기마다 답변에 대한 맞춤법 검사를 실행할 수 있도록 하고 싶은데요. 

크롬 확장 프로그램 형태로도 개발하실 계획이 있으신지 궁금하구요. 
그렇지 않다고 하시더라도 본 깃허브의 라이센스를 획득하여 저희 회사 내에서 자체적으로 크롬 확장 프로그램을 개발하는 형태도 문제는 없겠습니다. 

혹시 본 깃허브의 기업용 라이센스를 구매하고자 한다면 여기에 남기면 될지요?

**Comment by 9beach** [comment]
일단 한스펠 자바스크립트 API로 크롬 확장 프로그램을 개발하는 것은 MIT 라이센스라서 무료입니다. 그런데 한스펠도 자체 서비스가 아니라 다음과 부산대의 서비스를 이용합니다. 제 생각에 부산대 서비스는 변경도 잦고 원하시는 일에 그리 친화적이지 않아서, 한스펠 다음 API로 크롬 확장 프로그램을 만들면 문제가 없지 않을까 생각하는데 확답을 해드리기 힘듭니다.

다음이나 부산대는 자체적으로 웹 서비스를 제공합니다. 차라리 해당 웹서비스를 사용해서 답변을 달아드리도록 가이드하는 것이 어떨까요?
